name: Run Jest testing suite
on:
  workflow_dispatch:
  pull_request:

env:
  NODE_ENV: "test"

jobs:
  testing:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v2

      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Run Main Jest Suite
        run: bun run test

      - name: Run CI Jest Suite
        run: bun run test:ci

      - name: Add Jest Report to Summary (Main)
        if: always()
        run: echo "$(cat test-dashboard.md)" >> $GITHUB_STEP_SUMMARY

      - name: Add Jest Report to Summary (CI)
        if: always()
        run: echo "$(cat CI/test-dashboard.md)" >> $GITHUB_STEP_SUMMARY
